image: nikolaik/python-nodejs:latest

cache:
  paths:
    - node_modules/

stages:
  - production
  - develop

before_script:
  - pip install awscli
  - npm install
  - npm run build:dev

deploy_dev:
  stage: develop
  script:
    - aws s3 sync build s3://$AWS_BUCKET_DEV --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_DEV --paths '/*'
    - echo "DEPLOYED SUCCESSFULLY DEV"
  only:
    - develop

deploy_prod:
  stage: production
  script:
    - aws s3 sync build s3://$AWS_BUCKET_PROD --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_PROD --paths '/*'
    - echo "DEPLOYED SUCCESSFULLY PROD"
  only:
    - master
